services:
  shield-app:
    build:
      context: .
    container_name: shield-app
    expose:
      - "9000"  # só expõe internamente para o nginx
    networks:
      - shield-net

  nginx-app:
    build:
      context: ./nginx
    container_name: nginx-app
    ports:
      - "80:80"  # host:container, agora acessível em localhost:8080
    depends_on:
      - shield-app
    networks:
      - shield-net

networks:
  shield-net:
    driver: bridge
