services:
  shield-app:
    build: .
    container_name: shield-app
    ports:
      - "9000:8080"
    expose:
      - "9000"
    networks:
      - shield-net

  nginx-app:
    build: ./nginx
    container_name: nginx-app
    ports:
      - "80:80"   # Agora o Nginx expõe direto na porta 80 do host
    depends_on:
      - shield-app
    networks:
      - shield-net

networks:
  shield-net:
    driver: bridge
